/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accords */
        get: operations["list_accords_api_v1_accords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accords/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Accord */
        get: operations["get_accord_api_v1_accords__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_v1_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_api_v1_articles__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brands */
        get: operations["list_brands_api_v1_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/brands/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brand */
        get: operations["get_brand_api_v1_brands__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Stream a fragrance recommendation turn as SSE events.
         *
         *     Pre-stream gates run in this order (all errors return JSON envelopes
         *     BEFORE the stream opens):
         *
         *       1. Pydantic body validation (last-must-be-user, char + count caps).
         *       2. tiktoken per-message token count vs `MAX_TOKENS_PER_MESSAGE`.
         *       3. Redis daily kill-switch INCR + cap.
         *       4. slowapi per-IP h + d windows (decorators above).
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fragrances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fragrances */
        get: operations["list_fragrances_api_v1_fragrances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fragrances/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fragrance */
        get: operations["get_fragrance_api_v1_fragrances__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fragrances/{slug}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Similar Fragrances
         * @description Return fragrances similar to `{slug}` using its stored embedding.
         *
         *     Shares the per-IP rate limit and daily kill-switch with `/search`.
         *     Does NOT call OpenAI: the embedding is loaded from `fragrance_embeddings`.
         */
        post: operations["similar_fragrances_api_v1_fragrances__slug__similar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_v1_notes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Note */
        get: operations["get_note_api_v1_notes__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Perfumers */
        get: operations["list_perfumers_api_v1_perfumers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfumers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Perfumer */
        get: operations["get_perfumer_api_v1_perfumers__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Hybrid pgvector + FTS + ontology search.
         */
        post: operations["search_api_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe. MUST NOT touch DB/Redis.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe. S7: error message is generic; full exception is
         *     logged server-side so connection strings, hostnames, or driver-leaked
         *     credentials never reach the response body.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccordDetail */
        AccordDetail: {
            fragrances: components["schemas"]["ListEnvelope_FragranceListItem_"];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** AccordSummary */
        AccordSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** AccordsListResponse */
        AccordsListResponse: {
            /** Data */
            data: components["schemas"]["AccordSummary"][];
        };
        /** ArticleDetail */
        ArticleDetail: {
            /** Body */
            body: string | null;
            /** Fragrances */
            fragrances: components["schemas"]["FragranceListItem"][];
            /** Published At */
            published_at: string | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** ArticleSummary */
        ArticleSummary: {
            /** Published At */
            published_at?: string | null;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
        };
        /** BrandDetail */
        BrandDetail: {
            fragrances: components["schemas"]["ListEnvelope_FragranceListItem_"];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** BrandSummary */
        BrandSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * ChatMessage
         * @description One conversation message. `role=user|assistant|system` per the
         *     api-app spec request body. `content` is char-capped here as a cheap
         *     pre-check before tokenization (see `MAX_TOKENS_PER_MESSAGE`).
         */
        ChatMessage: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
        };
        /**
         * ChatRequest
         * @description `POST /api/v1/chat` body.
         *
         *     `session_id` is opaque telemetry per agent spec "No Checkpointer In V1"
         *     — never used to drive any state-store read or write.
         */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Session Id */
            session_id?: string | null;
        };
        /** ConcentrationSummary */
        ConcentrationSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * FilterSpec
         * @description Structured catalog filters; mirrors the P1 list-endpoint filters.
         */
        FilterSpec: {
            /** Accord */
            accord?: string[];
            /** Brand */
            brand?: string | null;
            /** Concentration */
            concentration?: string | null;
            /** Gender */
            gender?: ("masculine" | "feminine" | "unisex") | null;
            /** Note */
            note?: string[];
            /** Year Max */
            year_max?: number | null;
            /** Year Min */
            year_min?: number | null;
        };
        /** FragranceDetail */
        FragranceDetail: {
            /** Accords */
            accords: components["schemas"]["AccordSummary"][];
            /** Articles */
            articles: components["schemas"]["ArticleSummary"][];
            brand: components["schemas"]["BrandSummary"];
            concentration: components["schemas"]["ConcentrationSummary"] | null;
            /** Description */
            description: string | null;
            /** Gender */
            gender: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            notes: components["schemas"]["NotesByRole"];
            /** Perfumers */
            perfumers: components["schemas"]["PerfumerSummary"][];
            /** Slug */
            slug: string;
            /** Year Released */
            year_released: number | null;
            /** Year Text */
            year_text: string | null;
        };
        /** FragranceListItem */
        FragranceListItem: {
            brand: components["schemas"]["BrandSummary"];
            concentration: components["schemas"]["ConcentrationSummary"] | null;
            /** Gender */
            gender: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Year Released */
            year_released: number | null;
        };
        /**
         * Gender
         * @description Maps to PG ENUM ``fragrance_gender``.
         * @enum {string}
         */
        Gender: "masc" | "fem" | "unisex" | "genderfree";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ListEnvelope[ArticleSummary] */
        ListEnvelope_ArticleSummary_: {
            /** Data */
            data: components["schemas"]["ArticleSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** ListEnvelope[BrandSummary] */
        ListEnvelope_BrandSummary_: {
            /** Data */
            data: components["schemas"]["BrandSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** ListEnvelope[FragranceListItem] */
        ListEnvelope_FragranceListItem_: {
            /** Data */
            data: components["schemas"]["FragranceListItem"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** ListEnvelope[PerfumerSummary] */
        ListEnvelope_PerfumerSummary_: {
            /** Data */
            data: components["schemas"]["PerfumerSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** NoteDetail */
        NoteDetail: {
            fragrances: components["schemas"]["ListEnvelope_FragranceListItem_"];
            /** Name */
            name: string;
            parent: components["schemas"]["NoteSummary"] | null;
            /** Slug */
            slug: string;
        };
        /** NoteSummary */
        NoteSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** NoteTreeEnvelope */
        NoteTreeEnvelope: {
            /** Data */
            data: components["schemas"]["NoteTreeNode"][];
        };
        /**
         * NoteTreeNode
         * @description Self-recursive tree node used by GET /api/v1/notes.
         */
        NoteTreeNode: {
            /** Children */
            children?: components["schemas"]["NoteTreeNode"][];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** NotesByRole */
        NotesByRole: {
            /**
             * Base
             * @default []
             */
            base: components["schemas"]["NoteSummary"][];
            /**
             * Heart
             * @default []
             */
            heart: components["schemas"]["NoteSummary"][];
            /**
             * Top
             * @default []
             */
            top: components["schemas"]["NoteSummary"][];
        };
        /** Pagination */
        Pagination: {
            /** Has Next */
            has_next: boolean;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PerfumerDetail */
        PerfumerDetail: {
            fragrances: components["schemas"]["ListEnvelope_FragranceListItem_"];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** PerfumerSummary */
        PerfumerSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * SearchHit
         * @description One ranked candidate in the search response.
         */
        SearchHit: {
            fragrance: components["schemas"]["FragranceListItem"];
            /** Match Reason */
            match_reason: ("vector" | "fts" | "ontology")[];
            /** Relevance Score */
            relevance_score: number;
        };
        /**
         * SearchRequest
         * @description `POST /api/v1/search` body.
         */
        SearchRequest: {
            filters?: components["schemas"]["FilterSpec"];
            /** Include */
            include?: ("notes" | "brand" | "perfumer")[];
            /** Query */
            query: string;
            /**
             * Top K
             * @default 20
             */
            top_k: number;
        };
        /**
         * SearchResponse
         * @description Envelope returned by both `/search` and `/{slug}/similar`.
         */
        SearchResponse: {
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
            /** Data */
            data: components["schemas"]["SearchHit"][];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
        };
        /**
         * SimilarRequest
         * @description `POST /api/v1/fragrances/{slug}/similar` body.
         */
        SimilarRequest: {
            /** Include */
            include?: ("notes" | "brand" | "perfumer")[];
            /**
             * Top K
             * @default 20
             */
            top_k: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accords_api_v1_accords_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccordsListResponse"];
                };
            };
        };
    };
    get_accord_api_v1_accords__slug__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccordDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_v1_articles_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_ArticleSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_v1_articles__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brands_api_v1_brands_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_BrandSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brand_api_v1_brands__slug__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fragrances_api_v1_fragrances_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                brand?: string | null;
                perfumer?: string[] | null;
                gender?: components["schemas"]["Gender"] | null;
                year_min?: number | null;
                year_max?: number | null;
                concentration?: string | null;
                accord?: string[] | null;
                note?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_FragranceListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fragrance_api_v1_fragrances__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FragranceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_fragrances_api_v1_fragrances__slug__similar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_v1_notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteTreeEnvelope"];
                };
            };
        };
    };
    get_note_api_v1_notes__slug__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_perfumers_api_v1_perfumers_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvelope_PerfumerSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_perfumer_api_v1_perfumers__slug__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfumerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
